@host = http://localhost
@port = 3500
@endpoint = auth

@url = {{host}}:{{port}}/{{endpoint}} 

###
GET {{url}}

###
# registrar um novo usuario
POST  {{url}}/register
Content-Type: application/json; charset=utf-8

{
      "name": "prova 020",
      "password": "020",
      "email" : "provara020@fatec.com"
    }

###

###
# inclui novos registros
POST  {{url}}/login
Content-Type: application/json; charset=utf-8

{
      "name": "prova 022",
      "password": "022",
      "email" : "provara022@fatec.com"
    }

###

PUT  {{url}}/5
Content-Type: application/json; charset=utf-8

{
    "userName": "teste.022",
    "userPassword": "123-456"    
}

###
DELETE  {{url}}/12
