@host = http://localhost
@port = 3500
@endpoint = estados

@url = {{host}}:{{port}}/{{endpoint}} 

###
GET {{url}}

###
# getById
GET {{url}}/4

###
# inclui novos registros
POST  {{url}}
Content-Type: application/json; charset=utf-8

{
      "estado": "Brasilia",
      "uf": "DF"
    }

###

PUT  {{url}}/4
Content-Type: application/json; charset=utf-8

{
      "estado": "Distrito Federal",
      "uf": "DF"
    }


###
DELETE  {{url}}/4