@host = http://192.168.10.48
@port = 3500
@endpoint = municipios

@url = {{host}}:{{port}}/{{endpoint}} 

###
GET {{url}}

###
# getById
GET {{url}}/2

###
# inclui novos registros
POST  {{url}}
Content-Type: application/json; charset=utf-8

{
  "municipio": "Ibitinga",
   "UF": "SP"
}

###

PUT  {{url}}/6
Content-Type: application/json; charset=utf-8

{
  "municipio": "Itápolis",
   "uf": "SP"
}

###
DELETE  {{url}}/6