@host = http://localhost
@port = 3500
@endpoint = users

@url = {{host}}:{{port}}/{{endpoint}} 

###
GET {{url}}

###
# getById
GET {{url}}/5

###
# inclui novos registros
POST  {{url}}
Content-Type: application/json; charset=utf-8

{
      "userName": "provara022@fatec.com",
      "userPassword": "022"
    }

###

PUT  {{url}}/5
Content-Type: application/json; charset=utf-8

{
    "userName": "teste.022",
    "userPassword": "123-456"    
}

###
DELETE  {{url}}/2